### ISSUE TITLE
Wrong Exception thrown 

### ISSUE THREAD

**Issue by tharindulak** [wso2-extensions/siddhi-map-binary#15]
**Description:**
In @map(type='binary')) , when the source stream does not math with the client sending events, it throws up a java.lang.OutOfMemoryError: Java heap space error. 
![screenshot from 2017-11-22 10-31-02](https://user-images.githubusercontent.com/20821008/33111831-0d10e866-cf76-11e7-8465-772006202436.png)
The code is same as the Siddhi query guide with an extra stream variable as name string. 

Error looks as follows
![screenshot from 2017-11-22 10-31-33](https://user-images.githubusercontent.com/20821008/33111919-7b049ef8-cf76-11e7-9218-e1bb9ac2893b.png)

This error occurred due to an incompatibility issue in source stream and sent events. 

**Suggested Labels:**
Bug

**Affected Product Version:**
4.0.0

**Comment by suhothayan** [comment]
Can give the sample message you sent as well

**Comment by mohanvive** [comment]
Not reproducible with latest binary mapper implementation.
